# Generated by Django 3.2.2 on 2021-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_companion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_budget',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
